name: Main CI
   
on:
  push:
    branches:
      - main
   
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
   
      - name: yarn install
        run: yarn install
   
      - name: yarn build
        run: yarn run build
   
      - name: deploy
        env:
          AWS_ACCESS_KEY: '${{secrets.AWS_ACCESS_KEY}}'
          AWS_SECRET_KEY: '${{secrets.AWS_SECRET_KEY}}'
        run:
          aws s3 cp --recursive --region ap-northeast-2 out s3://blog-ycow
   
